[general]
import = [ "~/.config/alacritty/dark_theme.toml", "~/.config/alacritty/keybindings.toml" ]

[font]
size = 14.0

[font.normal]
family = "SFMono Nerd Font"

[env]
TERM = "alacritty"
COLORTERM = "truecolor"

[colors.cursor]
cursor = "#FC2A1C"

[window]
decorations = "buttonless"
dynamic_title = true
title = "Terminal"

[window.dimensions]
columns = 81
lines = 25

[window.padding]
x = 0
y = 0
